# Generated by Django 5.0.1 on 2024-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Students_Id',
            field=models.IntegerField(default=0),
        ),
    ]
