# Generated by Django 5.0.1 on 2024-01-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapi', '0002_students_students_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
